### ISSUE TITLE
Update repo to come in compliance with Influenza OSS SOP

### ISSUE THREAD

**Issue by leebrian** [CDCgov/app-squared#1]
Read through [SOP](https://flu-informatics.pages.biotech.cdc.gov/idkb/docs/sop/open_source_sop.html) [intranet link] and bring this repo up to speed. This will cover all the CDC policies and whatnot.

**Comment by nicolepaterson** [comment]
Updated the readme to comply with CDC policy on open source projects. Included additional background on the project and links to related repositories.
