### ISSUE TITLE
Please add cdc-influenza-division topic

### ISSUE THREAD

**Issue by leebrian** [CDCgov/app-squared#11]
To help people find and use your project, would you please add some topics/keywords (per the CDC open practices guide, https://github.com/CDCgov/template/blob/main/open_practices.md#required-practices).

Since you're in ID, please add `cdc-influenza-division` in addition to `ncird-id` (per the ID SOP https://flu-informatics.pages.biotech.cdc.gov/idkb/docs/policy_sop/open_source_sop.html [intranet only]).

I noticed this when I was looking up some stats for a report out. I'm adding this issue to all our repos that don't have it, but if I forget one, please go ahead and update any you know about.

**Comment by nicolepaterson** [comment]
will do!
